using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;
//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace campingplan.Models
{
    [MetadataType(typeof(ProductMetaData))]
    [Bind(Exclude = "varify_code,isvarify")]
    public partial class product
    {

        private class ProductMetaData
        {
            [Key]
            public int rowid { get; set; }
            [DisplayName("商品種類")]
            public Nullable<int> categoryid { get; set; }

            [Required(ErrorMessage = "不可空白!!")]
            [DisplayFormat(ApplyFormatInEditMode = true, ConvertEmptyStringToNull = false, HtmlEncode = true)]
            [DisplayName("商品編號")]
            public string pno { get; set; }

            [Required(ErrorMessage = "不可空白!!")]
            [DisplayFormat(ApplyFormatInEditMode = true, ConvertEmptyStringToNull = false, HtmlEncode = true)]
            [DisplayName("商品名稱")]
            public string pname { get; set; }

            [Required(ErrorMessage = "不可空白!!")]
            [DisplayFormat(ApplyFormatInEditMode = true, ConvertEmptyStringToNull = false, HtmlEncode = true)]
            [DisplayName("商品內容")]
            public string pdescription { get; set; }

            //[Required(ErrorMessage = "不可空白!!")]
            //[DisplayFormat(ApplyFormatInEditMode = true, ConvertEmptyStringToNull = false, HtmlEncode = true)]
            //[DisplayName("價錢")]
            //public Nullable<int> pprice { get; set; }

            [DisplayName("圖片")]
            public string pimg { get; set; }

            [Required(ErrorMessage = "不可空白!!")]
            [DisplayFormat(ApplyFormatInEditMode = true, ConvertEmptyStringToNull = false, HtmlEncode = true)]
            [DisplayName("地點")]
            public string plocation { get; set; }
        }
    }
}