using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;
//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace campingplan.Models
{
    [MetadataType(typeof(ProductsMetaData))]
    public partial class product
    {
        [Display(Name = "熱門")]
        public bool bool_istop { get; set; }
        [Display(Name = "上架")]
        public bool bool_issale { get; set; }
        [Display(Name = "顏色")]
        public bool bool_iscolor { get; set; }
        [Display(Name = "尺寸")]
        public bool bool_issize { get; set; }
        private class ProductsMetaData
        {
            [Key]
            [Display(Name = "記錄ID")]
            public int rowid { get; set; }
            [Display(Name = "分類ID")]
            public Nullable<int> categoryid { get; set; }
            [Display(Name = "商品分類")]
            public string category_name { get; set; }
            [Display(Name = "熱門商品")]
            public Nullable<int> istop { get; set; }
            [Display(Name = "上架銷售")]
            public Nullable<int> issale { get; set; }
            [Display(Name = "區分顏色")]
            public Nullable<int> iscolor { get; set; }
            [Display(Name = "區分尺寸")]
            public Nullable<int> issize { get; set; }
            [Display(Name = "自定尺寸")]
            public string size_name { get; set; }
            [Display(Name = "自定顏色")]
            public string color_name { get; set; }
            [Display(Name = "瀏覽次數")]
            public Nullable<int> browse_count { get; set; }
            [Display(Name = "廠商編號")]
            public string vendor_no { get; set; }
            [Display(Name = "商品編號")]
            public string product_no { get; set; }
            [Display(Name = "商品名稱")]
            public string product_name { get; set; }
            [Display(Name = "商品規格")]
            public string product_spec { get; set; }
            [Display(Name = "銷售單價")]
            public Nullable<int> price { get; set; }
            [Display(Name = "推薦星數")]
            public Nullable<int> start_count { get; set; }
            [Display(Name = "備註")]
            public string remark { get; set; }
        }
    }
}