//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace campingplan.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class customer
    {
        public int rowid { get; set; }
        public string mno { get; set; }

        [DisplayName("帳號")]
        [Required]
        public string maccount { get; set; }

        [DisplayName("密碼")]
        [Required(ErrorMessage ="密碼不可空白")]
        public string mpassword { get; set; }

        [DisplayName("暱稱")]
        [Required]
        public string mnickname { get; set; }

        [DisplayName("電子信箱")]
        [Required]
        [EmailAddress]
        public string memail { get; set; }

        [DisplayName("生日")]
        public Nullable<System.DateTime> birth_date { get; set; }
    }
}
