//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace campingplan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class product_features
    {
        public int rowid { get; set; }
        public string pno { get; set; }
        public Nullable<int> location_type { get; set; }
        public Nullable<int> near_river { get; set; }
        public Nullable<int> near_sea { get; set; }
        public Nullable<int> no_tent { get; set; }
        public Nullable<int> have_canopy { get; set; }
        public Nullable<int> have_clouds { get; set; }
        public Nullable<int> have_firefly { get; set; }
        public Nullable<int> could_book_all { get; set; }
        public Nullable<int> have_rental_equipment { get; set; }
        public Nullable<int> have_game_area { get; set; }
        public Nullable<int> elevation_under_300m { get; set; }
        public Nullable<int> elevation_301m_to_500m { get; set; }
        public Nullable<int> elevation_over_501m { get; set; }
    
        public virtual product product { get; set; }
    }
}
