//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace campingplan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public product()
        {
            this.product_typedetail = new HashSet<product_typedetail>();
        }
    
        public int rowid { get; set; }
        public Nullable<int> categoryid { get; set; }
        public string pno { get; set; }
        public string plocation { get; set; }
        public string pname { get; set; }
        public string pdescription { get; set; }
        public System.DateTime psetdate { get; set; }
        public string pimg { get; set; }
        public Nullable<int> pstatus { get; set; }
        public string pmapurl { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<product_typedetail> product_typedetail { get; set; }
        public virtual product_features product_features { get; set; }
    }
}
